#!/usr/bin/env bash
# Write worker/.dev.vars from:
#   1) ~/.config/ai-providers/env.local  (StepFun TTS/ASR, optional XAI)
#   2) ~/.cli-proxy-api/client.env       (8317 OpenAI-compatible key for Grok)
# Never print secret values.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${AI_PROVIDERS_ENV:-$HOME/.config/ai-providers/env.local}"
CLI_PROXY_ENV="${CLI_PROXY_ENV:-$HOME/.cli-proxy-api/client.env}"
DEST="$ROOT/worker/.dev.vars"

if [[ ! -f "$SRC" ]]; then
  echo "missing secrets file: $SRC" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "$SRC"
if [[ -f "$CLI_PROXY_ENV" ]]; then
  # shellcheck disable=SC1090
  source "$CLI_PROXY_ENV"
fi
set +a

: "${STEPFUN_API_KEY:?STEPFUN_API_KEY missing in $SRC}"

MINIMAX_KEY="${MINIMAX_API_KEY:-${MINIMAX_TOKEN_PLAN_KEY:-}}"
if [[ -z "$MINIMAX_KEY" ]]; then
  echo "MINIMAX_API_KEY (or MINIMAX_TOKEN_PLAN_KEY) missing in $SRC — required for TTS" >&2
  exit 1
fi

# Chat defaults to Grok via local cli-proxy (8317). Override with env if needed.
CHAT_BASE="${CHAT_BASE:-http://127.0.0.1:8317/v1}"
CHAT_MODEL="${CHAT_MODEL:-grok-4.5}"

# Prefer explicit chat key, then cli-proxy OPENAI_API_KEY, then XAI, else StepFun.
CHAT_API_KEY="${CHAT_API_KEY:-${OPENAI_API_KEY:-${XAI_API_KEY:-$STEPFUN_API_KEY}}}"

if [[ -z "$CHAT_API_KEY" ]]; then
  echo "CHAT_API_KEY unresolved (need OPENAI_API_KEY from cli-proxy, XAI_API_KEY, or STEPFUN)" >&2
  exit 1
fi

# If we fell back to StepFun key and user did not force CHAT_BASE, keep StepFun chat base.
if [[ "$CHAT_API_KEY" == "$STEPFUN_API_KEY" && -z "${OPENAI_API_KEY:-}" && -z "${XAI_API_KEY:-}" ]]; then
  if [[ "$CHAT_BASE" == "http://127.0.0.1:8317/v1" ]]; then
    CHAT_BASE="https://api.stepfun.com/v1"
    CHAT_MODEL="${STEPFUN_CHAT_MODEL:-step-3.7-flash}"
  fi
fi

umask 077
cat >"$DEST" <<EOF
# Generated by scripts/sync-dev-vars-from-ai-providers.sh — do not commit.
# Chat/vision (Grok family via OpenAI-compatible upstream)
CHAT_API_KEY=${CHAT_API_KEY}
CHAT_BASE=${CHAT_BASE}
CHAT_MODEL=${CHAT_MODEL}

# MiniMax TTS (t2a_v2)
MINIMAX_API_KEY=${MINIMAX_KEY}
MINIMAX_TTS_MODEL=${MINIMAX_TTS_MODEL:-speech-2.8-hd}
MINIMAX_VOICE_ID=${MINIMAX_VOICE_ID:-shangqiuzi_v3_20260717}
MINIMAX_TTS_URL=${MINIMAX_TTS_URL:-https://api.minimaxi.com/v1/t2a_v2}

# StepFun Token Plan — ASR (and optional chat fallback)
STEPFUN_API_KEY=${STEPFUN_API_KEY}
STEPFUN_CHAT_MODEL=${STEPFUN_CHAT_MODEL:-step-3.7-flash}
STEPFUN_CHAT_BASE=https://api.stepfun.com/v1
STEPFUN_ASR_MODEL=${STEPFUN_ASR_MODEL:-stepaudio-2.5-asr}
EOF

echo "wrote $DEST (mode 600, values not printed)"
echo "chat: base=$CHAT_BASE model=$CHAT_MODEL key=set"
echo "tts: minimax key=set model=${MINIMAX_TTS_MODEL:-speech-2.8-hd}"
echo "asr: stepfun key=set"
ls -l "$DEST"
